// import custom components
import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";

export default function Layout({ children }) {
	return (
		<>
			<Head>
				<title>EVG Texas</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="height=device-height, 
                      width=device-width, initial-scale=1.0, 
                      minimum-scale=1.0, maximum-scale=1.0, 
                      user-scalable=no, target-densitydpi=device-dpi"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<Navbar />
			<main>{children}</main>
			<Footer />
		</>
	);
}
